owner: bullwinkle-org # Your GitHub username
repo: monitor-uptime # Your GitHub repository name

user-agent: bullwinkle

assignees:
  - bullwinkle

status-website:
  links:
    - rel: stylesheet
      href: https://bullwinkle-org.github.io/monitor-uptime/styles-test.css
  name: "Bullwinkle_Upptime"
  cname: monitor.bullwinkle.ml # if you use custom domain
  theme: dark # light, dark, ocean
  logoUrl: https://avatars.githubusercontent.com/u/77125363?s=400&u=62255c8e27ec580174f0c620b87c950a4d18f982&v=4
  introTitle: "**Bullwinkle's org** uptime monitor and status page, powered entirely by GitHub."
  introMessage: "internal stuff monitoring"
  navbar:
    - title: Status
      href: /

    - title: "Bullwinkle's org on GitHub"
      href: https://github.com/$OWNER

    - title: "Current repo page on GitHub"
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: bullwinkle.ml
    url: https://bullwinkle.ml

  - name: static.bullwinkle.ml
    url: https://static.bullwinkle.ml

  - name: ui.bullwinkle.ml
    url: https://ui.bullwinkle.ml

  - name: data.bullwinkle.ml
    url: https://data.bullwinkle.ml

  - name: db.bullwinkle.ml
    url: https://db.bullwinkle.ml

  - name: workspace.bullwinkle.ml
    url: https://workspace.bullwinkle.ml

  - name: realm-one-app.bullwinkle.ml
    url: https://realm-one-app.bullwinkle.ml


skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

#  - name: google.com
#    url: https://google.com
#    method: POST
#    headers:
#      - "Authorization: Bearer $SECRET_SITE_2"
#      - "Content-Type: application/json"
#    body: '{ "password": "hello" }'
#    assignees:
#      - AnandChowdhary
#    maxResponseTime: 5000
#    expectedStatusCodes:
#      - 200
#      - 201
#      - 404
#    __dangerous__disable_verify_peer: true
#    __dangerous__disable_verify_host: true
#    __dangerous__insecure: true
#    __dangerous__body_down: "File not found"
#    __dangerous__body_degraded: "Site degraded"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
