owner: bullwinkle-org # Your GitHub username
repo: monitor-uptime  # Your GitHub repository name

user-agent: bullwinkle

assignees:
  - bullwinkle-org

status-website:
  name: "Bullwinkle's org upptime"
  theme: dark # light, dark, ocean
  cname: monitor.bullwinkle.ml # if you use custom domain
  # baseUrl: /monitor-uptime # if you DO NOT use custom domain
  apiBaseUrl: https://api.github.com
  themeUrl: /css/bullwinkle-theme-dark.css
  logoUrl: /images/brand.png
  favicon: /images/icon.png
  # faviconSvg: https://example.com/logo.svg
  scripts:
    - src: /js/script-1.js
    - src: /js/script-2.js
      async: true
  js: "window.onload = function() { alert('Hello!') }"
  links:
    - rel: stylesheet
      href: /css/script-1.js
  css: "body { opacity: 0.5 }"
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  introTitle: "**Bullwinkle's org** uptime monitor and status page, powered entirely by GitHub."
  introMessage: "internal stuff monitoring"
  customHeadHtml: "<!-- Custom HTML to add in the <head> tag -->"
  customBodyHtml: "<!-- Custom HTML to add at the beginning of <body> -->"

  navbar:
    - title: Status
      href: /

    - title: About
      href: /about

    - title: "Bullwinkle's org on GitHub"
      href: https://github.com/$OWNER

    - title: "Current repo page on GitHub"
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: bullwinkle.ml
    url: https://bullwinkle.ml

  - name: static.bullwinkle.ml
    url: https://static.bullwinkle.ml

  - name: ui.bullwinkle.ml
    url: https://ui.bullwinkle.ml

  - name: data.bullwinkle.ml
    url: https://data.bullwinkle.ml

  - name: db.bullwinkle.ml
    url: https://db.bullwinkle.ml

  - name: workspace.bullwinkle.ml
    url: https://workspace.bullwinkle.ml

  - name: realm-one-app.bullwinkle.ml
    url: https://realm-one-app.bullwinkle.ml

#  - name: google.com
#    url: https://google.com
#    method: POST
#    headers:
#      - "Authorization: Bearer $SECRET_SITE_2"
#      - "Content-Type: application/json"
#    body: '{ "password": "hello" }'
#    assignees:
#      - AnandChowdhary
#    maxResponseTime: 5000
#    expectedStatusCodes:
#      - 200
#      - 201
#      - 404
#    __dangerous__disable_verify_peer: true
#    __dangerous__disable_verify_host: true
#    __dangerous__insecure: true
#    __dangerous__body_down: "File not found"
#    __dangerous__body_degraded: "Site degraded"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
