# Change these first
owner: bullwinkle-org # Your GitHub username
repo: monitor-uptime  # Your GitHub repository name

# Add your sites here
sites:
  - name: $ORG_DOMAIN
    url: $ORG_DOMAIN
    
assignees:
  - Bullwinkle

status-website:
  theme: dark
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: monitor.$ORG_DOMAIN
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /monitor-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bullwinkle's org upptime
  introTitle: "**Bullwinkle's org** uptime monitor and status page, powered entirely by GitHub."
  introMessage: internal stuff monitoring
  navbar:
    - title: Status
      href: /
    - title: "$OWNER on GitHub"
      href: https://github.com/$OWNER
    - title: "$REPO on GitHub (this repo)"
      href: https://github.com/$OWNER/$REPO
    - title: ${{ repo }} on GitHub (this repo)
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
