owner: bullwinkle-org # Your GitHub username
repo: monitor-uptime  # Your GitHub repository name

assignees:
  - bullwinkle
  
user-agent: bullwinkle  

sites:
  - name: bullwinkle.ml
    url: https://bullwinkle.ml

  - name: ui.bullwinkle.ml
    url: https://ui.bullwinkle.ml

  - name: db.bullwinkle.ml
    url: https://db.bullwinkle.ml

  - name: workspace.bullwinkle.ml
    url: https://workspace.bullwinkle.ml

  - name: realm-app-one.bullwinkle.ml
    url: https://realm-app-one.bullwinkle.ml

status-website:
  name: "Bullwinkle's org upptime"
  cname: monitor.bullwinkle.ml
  # Custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /monitor-uptime
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Bullwinkle's org** uptime monitor and status page, powered entirely by GitHub."
  introMessage: "internal stuff monitoring"
  navbar:
    - title: Status
      href: /

    - title: "Bullwinkle's org on GitHub"
      href: https://github.com/$OWNER

    - title: "Current repo page on GitHub"
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
