owner: bullwinkle-org # Your GitHub username
repo: monitor-uptime # Your GitHub repository name

sites:
  - name: Bullwinkle and friends
    url: https://bullwinkle.ml
    icon: https://bullwinkle.ml/favicon.ico

status-website:
  name: "Bullwinkle and friends"
  cname: monitor.bullwinkle.ml # if you use custom domain
  baseUrl: /
  apiBaseUrl: https://api.github.com
  theme: dark # light, dark, ocean
  favicon: https://bullwinkle.ml/favicon.ico
  faviconSvg: https://bullwinkle.ml/assets/favicon/favicon.svg

  introTitle: "Uptime status page for **Bullwinkle and friends**"
  introMessage: "Monitoring organization's web stuff. Powered by GitHub."

  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"

  themeUrl: https://bullwinkle.ml/assets/css/upptime-monitor__theme-dark.css
  logoUrl: https://bullwinkle.ml/assets/images/brand.png
  links:
    - rel: stylesheet
      href: https://bullwinkle.ml/assets/css/styles-test.css
  scripts:
    - src: https://bullwinkle.ml/assets/js/script-1.js
    - src: https://bullwinkle.ml/assets/js/script-2.js
      async: true

  css: "body { font-size: initial; }"
  js: "window.onload = function() { console.warn('app started'); }"

  customHeadHtml: "<!-- Custom HTML to add in the <head> tag -->"
  customBodyHtml: "<!-- Custom HTML to add at the beginning of <body> -->"

  navbar:
    - title: Status
      href: /

    - title: "Bullwinkle's org on GitHub"
      href: https://github.com/$OWNER

    - title: "Current repo page on GitHub"
      href: https://github.com/$OWNER/$REPO

user-agent: bullwinkle

assignees:
  - bullwinkle

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

#  - name: google.com
#    url: https://google.com
#    method: POST
#    headers:
#      - "Authorization: Bearer $SECRET_SITE_2"
#      - "Content-Type: application/json"
#    body: '{ "password": "hello" }'
#    assignees:
#      - AnandChowdhary
#    maxResponseTime: 5000
#    expectedStatusCodes:
#      - 200
#      - 201
#      - 404
#    __dangerous__disable_verify_peer: true
#    __dangerous__disable_verify_host: true
#    __dangerous__insecure: true
#    __dangerous__body_down: "File not found"
#    __dangerous__body_degraded: "Site degraded"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
