title: Monitor uptime
theme: jekyll-theme-minimal
subtitle: "Public monitoring page"
description: "Description"
share: "Shared"
url: https://monitor.bullwinkle.ml
permalink: pretty
exclude: ['node_modules']
